

import 'dart:ui';
const Color primaryColor = Color(0xff009AFF);
// const Color primaryColor = Color(0xff0000AB);
const Color bgColor = Color(0xffE5E5E5);
const Color bottomAppColor = Color(0xffE5E5E5);
const Color borderColor = Color(0xffffffff);
const Color dividerColor = Color(0xffEEEEEE);
const Color accentColor = Color(0xff245161);
const Color hintColor = Color(0xff9A9A9A);
const Color disableColor = Color(0xffF8F8F8);
const Color canvasColor = Color(0xffffffff);
const Color categoriesTextColor=Color(0xff6D7277);
const Color defaultTextColor=Color(0xffFFFFFF);
const Color exclusiveOfferSubtextColor=Color(0xff3E3B41);
const Color categoriesTitleTextColor=Color(0xff6D7277);
const Color groupOrdersTitleTextColor=Color(0xff9CA0A8);
const Color groupOrdersAmountTextColor=Color(0xff4AA6FC);
const Color groupOrdersSoldItemsColor=Color(0xff4E555F);
const Color groupOrdersValuesColor=Color(0xff28292D);
const Color textOnClickColor=Color(0xff009AFF);
const Color productsTitleColor=Color(0xffF6F7FC);
const Color circledLoveButtonColor=Color(0xffE5E5E5);
const Color loveButtonColor=Color(0xffFFFFFF);
const Color viewAllColor=Color(0xff9CA0A8);
const Color bestSellingProductTitleColor=Color(0xff175394);
const Color actualPriceColor=Color(0xff3DB2FF);
const Color discountPriceColor=Color(0xffB4BABE);
const Color productSubTextColor=Color(0xff2C2C2C);
const Color additionalInfoTitleColor=Color(0xff30363C);
const Color additionalInfoSubtextColor=Color(0xff666666);
const Color contactTitleColor=Color(0xff3DB2FF);
const Color contactSubtextColor=Color(0xff31363D);
const Color clickOnOffersTitleColor=Color(0xff131921);
const Color secondScreenTitle=Color(0xff3D434A);
